import type { Metadata } from "next";

/**
 * Dex detail pages worth indexing: starters, tier-list staples, and Plausible traffic leaders.
 * Others stay noindex until content is thicker.
 */
export const INDEXABLE_DEX_SLUGS = [
  "bubble",
  "bubboxer",
  "bubblade",
  "blazpup",
  "blazgrowl",
  "leafbun",
  "mopebun",
  "pebble",
  "pebroll",
  "pebgolem",
  "sparkit",
  "emfox",
  "empixy",
  "clampip",
  "clamspire",
  "bluebird",
  "volcrest",
  "lavite",
  "lavarock",
  "frostlet",
  "frostseer",
  "tarro",
  "tarragon",
  "glowy",
  "glowres",
  "goliath",
  "arcub",
  "arcapex",
  "wispuff",
  "wisphex",
  "astraknight",
  // Map+combat thick batch (spawn + stats curated)
  "chirppy",
  "chirplume",
  "humding",
  "gulpfish",
  "mirefish",
  "clamwhirl",
  "budling",
  "vipip",
  "viparch",
  "fluffet",
  "fluffastar",
  "glaclide",
  "glacone",
  "glacitadel",
  "chitmite",
  "chitgladi",
  "chitaladin",
  "stardrift",
  "sundercrene",
  "spikub",
  "spikumane",
  "gempillar",
  "starloop",
  "starmuse",
  "tinkog",
  "tinkore",
  "pummpaw",
  "datubud",
  "datunymph",
  "mudbud",
  "mudthorn",
  // Season-1 batch (boss-reward + seasonal island lines, curated thick copy)
  "wispark",
  "wisflare",
  "wispreign",
  "clipdow",
  "cliphas",
  "clipexor",
  "clanx",
  "clanxor",
  // Line-fill batch (complete partially indexed evolution lines)
  "blazmane",
  "leafroge",
  "leafblade",
  "chirphantom",
  "flutterby",
  "twirlby",
  "mopillow",
  "florawn",
  "silvanarch",
  "vipour",
  "frostelle",
  "graycrene",
  "gempress",
  "pummash",
  "wispshade",
  "thordlord",
] as const;

export type IndexableDexSlug = (typeof INDEXABLE_DEX_SLUGS)[number];

export function isIndexableDexSlug(slug: string): slug is IndexableDexSlug {
  return (INDEXABLE_DEX_SLUGS as readonly string[]).includes(slug.toLowerCase());
}

/** Thin or utility pages: crawl links, skip indexing. */
export const NOINDEX_FOLLOW: Metadata["robots"] = {
  index: false,
  follow: true,
  googleBot: {
    index: false,
    follow: true,
    "max-image-preview": "large",
    "max-snippet": -1,
  },
};
